import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          {/* side-bar */}
          <div className="bg-black text-gray-200 max-w-[250px] overflow-y-auto md:min-w-[220px] min-h-screen">
            <SideBar />
          </div>
            <div>
            </div>
          <div className="bg-[#212121] flex-1 overflow-hidden h-screen relative text-gray-200">
            {/* Header */}
            <Header />
           {children}

          </div>
        </div>
      </body>
    </html>
  );
}
